apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ceph-demo
  name: ceph-demo
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: ceph-demo
